export default [
    {
      id: 1,
      name: "Name",
      type: "Residential",
      utility: "Utility",
      finance: "Finance Comp.",
      address: "Address",
      date: "16-03-2025",
      status: "Registered",
      hasIssue: true,
    },
    {
      id: 2,
      name: "Name",
      type: "Commercial",
      utility: "Utility",
      finance: "Finance Comp.",
      address: "Address",
      date: "16-03-2025",
      status: "Active",
      hasIssue: false,
    },
    {
      id: 3,
      name: "Name",
      type: "Commercial",
      utility: "Utility",
      finance: "Finance Comp.",
      address: "Address",
      date: "16-03-2025",
      status: "Invited",
      hasIssue: true,
    },
    {
      id: 4,
      name: "Name",
      type: "Resi. Group",
      utility: "Utility",
      finance: "Finance Comp.",
      address: "Address",
      date: "16-03-2025",
      status: "Active",
      hasIssue: false,
    },
    {
      id: 5,
      name: "Name",
      type: "Commercial",
      utility: "Utility",
      finance: "Finance Comp.",
      address: "Address",
      date: "16-03-2025",
      status: "Invited",
      hasIssue: true,
    },
    {
      id: 6,
      name: "Name",
      type: "Residential",
      utility: "Utility",
      finance: "Finance Comp.",
      address: "Address",
      date: "16-03-2025",
      status: "Active",
      hasIssue: false,
    },
    {
      id: 7,
      name: "Name",
      type: "Commercial",
      utility: "Utility",
      finance: "Finance Comp.",
      address: "Address",
      date: "16-03-2025",
      status: "Registered",
      hasIssue: true,
    },
    {
      id: 8,
      name: "Name",
      type: "Commercial",
      utility: "Utility",
      finance: "Finance Comp.",
      address: "Address",
      date: "16-03-2025",
      status: "Registered",
      hasIssue: true,
    },
    {
      id: 9,
      name: "Name",
      type: "Residential",
      utility: "Utility",
      finance: "Finance Comp.",
      address: "Address",
      date: "16-03-2025",
      status: "Registered",
      hasIssue: true,
    },
    {
      id: 10,
      name: "Name",
      type: "Residential",
      utility: "Utility",
      finance: "Finance Comp.",
      address: "Address",
      date: "16-03-2025",
      status: "Terminated",
      hasIssue: true,
    },
    // New entries start here
    {
      id: 11,
      name: "Alice Johnson",
      type: "Residential",
      utility: "Electric Co.",
      finance: "FinCorp Ltd.",
      address: "123 Maple Street",
      date: "10-01-2024",
      status: "Active",
      hasIssue: false,
    },
    {
      id: 12,
      name: "Bob Smith",
      type: "Commercial",
      utility: "Gas Services",
      finance: "Capital Finance",
      address: "456 Oak Avenue",
      date: "15-02-2024",
      status: "Invited",
      hasIssue: true,
    },
    {
      id: 13,
      name: "Charlie Brown",
      type: "Resi. Group",
      utility: "Water Works",
      finance: "Aqua Finance",
      address: "789 Pine Road",
      date: "20-03-2024",
      status: "Registered",
      hasIssue: false,
    },
    {
      id: 14,
      name: "Diana Prince",
      type: "Commercial",
      utility: "Solar Energy",
      finance: "Green Finance",
      address: "321 Birch Lane",
      date: "25-04-2024",
      status: "Terminated",
      hasIssue: true,
    },
    {
      id: 15,
      name: "Evan Davis",
      type: "Residential",
      utility: "Wind Power",
      finance: "Renewable Finance",
      address: "654 Cedar Drive",
      date: "01-06-2024",
      status: "Active",
      hasIssue: false,
    },
    {
      id: 16,
      name: "Fiona Gallagher",
      type: "Commercial",
      utility: "Nuclear Grid",
      finance: "Energy Capital",
      address: "987 Spruce Court",
      date: "10-07-2024",
      status: "Invited",
      hasIssue: true,
    },
    {
      id: 17,
      name: "George Lucas",
      type: "Residential",
      utility: "Hydro Co.",
      finance: "Blue Finance",
      address: "135 Willow Way",
      date: "15-08-2024",
      status: "Registered",
      hasIssue: false,
    },
    {
      id: 18,
      name: "Hannah Montana",
      type: "Commercial",
      utility: "Thermal Power",
      finance: "Heat Finance",
      address: "246 Redwood Path",
      date: "20-09-2024",
      status: "Active",
      hasIssue: false,
    },
    {
      id: 19,
      name: "Ian Fleming",
      type: "Resi. Group",
      utility: "GeoThermal",
      finance: "Earth Finance",
      address: "369 Elm Circle",
      date: "25-10-2024",
      status: "Terminated",
      hasIssue: true,
    },
    {
      id: 20,
      name: "Julia Roberts",
      type: "Residential",
      utility: "Coal Energy",
      finance: "Carbon Finance",
      address: "753 Ash Boulevard",
      date: "30-11-2024",
      status: "Invited",
      hasIssue: true,
    },
  ];